stages:
    - run_tox

before_script:
    - apt-get install software-properties-common
    - add-apt-repository -y ppa:deadsnakes/ppa
    - apt-get update -qy
    - apt-get install -y python3.8 python3-dev python3-pip tox

run_tox:
    stage: run_tox
    script:
        - tox